### ISSUE TITLE
Agent

### ISSUE THREAD

**Issue by nicosvg** [talan-labs/toast-tk-engine#67]

**Comment by skokaina** [comment]
- [x] Agent: be able to set the API key in the agent settings #79
- [x] Upgrade the agent to ensure that all the standard actions that are part of the selenium plugin are covered through the recording #81
- [x] Create a windows setup for the agent #82
