### ISSUE TITLE
Webapp updates for demo version

### ISSUE THREAD

**Issue by nicosvg** [talan-labs/toast-tk-engine#68]
**Enhancements needed to release a usable demo version of the webapp**
- [x] Campaign creation and update in the webapp #72
- [x] The user should be able to create a project (root object) #73 
- [x] The user should be able to define variables and use them in the scenario #74
- [ ] The user should be able to replay a scenario from the webapp as long as he's connected to an active agent #62 
- [x] Only one agent will be managed for a user, we'll need to monitor the agent state and have it displayed on the webapp, if the user switch to another test case, we should warn him that it will stop recording further actions and stop listening to the agent records #78
- [x] Have the ui template for the campaign reports integrated in the webapp, no more iFrame #69 

**Optional features**
- [ ] The user shall be able to tag scenarios #77
- [ ] Review the design of the login page #70

**Comment by Noki87** [comment]
- [ ] Review the design of the login page
- [ ] Have the ui template for the campaign reports integrated in the webapp, no more iFrame
- [ ] Allow campaign creation and update in the webapp
- [ ] The user should be able to create a project (root object)
- [ ] The user should be able to define variables and use them in the scenario
- [ ] The user should be able to replay a scenario from the webapp as long as he's connected to an active agent
- [ ] The user shall be able to tag scenarios
